Repository wisdom08/insta-backend, pull requests merged in 2022-08, with the labels that each got.

#3 헤로쿠 설정 추가
  Procfile
  build.gradle
  src/main/resources/application-prod.yaml
  system.properties
Labels: enhancement

#8 스웨거 추가
  build.gradle
  src/main/java/com/insta/config/SwaggerConfig.java
Labels: documentation

#13 공통적으로 쓸 수 있는 응답바디와 에러처리 추가
  src/main/java/com/insta/global/error/ErrorResponse.java
  src/main/java/com/insta/global/error/GlobalExceptionHandler.java
  src/main/java/com/insta/global/error/exception/BusinessException.java
  src/main/java/com/insta/global/error/exception/EntityNotFoundException.java
  src/main/java/com/insta/global/error/exception/ErrorCode.java
  src/main/java/com/insta/global/error/exception/InvalidValueException.java
  src/main/java/com/insta/global/response/ApiUtils.java
  src/main/java/com/insta/global/response/CommonResponse.java
Labels: enhancement

#14 게시글 쪽 코드 리팩토링
  src/main/java/com/insta/controller/ArticleController.java
  src/main/java/com/insta/dto/article/ArticleDetailResponseDto.java
  src/main/java/com/insta/dto/article/ArticleRequestDto.java
  src/main/java/com/insta/dto/article/ArticleResponseDto.java
  src/main/java/com/insta/global/error/exception/ErrorCode.java
  src/main/java/com/insta/model/Article.java
  src/main/java/com/insta/model/Articles.java
  src/main/java/com/insta/model/Timestamped.java
  src/main/java/com/insta/repository/ArticleRepo.java
  src/main/java/com/insta/repository/ArticleRepository.java
  src/main/java/com/insta/service/ArticleService.java
Labels: enhancement

#20 댓글/대댓글 기능 추가
  build.gradle
  src/main/java/com/insta/config/SwaggerConfig.java
  src/main/java/com/insta/config/WebConfig.java
  src/main/java/com/insta/controller/CommentController.java
  src/main/java/com/insta/controller/UserController.java
  src/main/java/com/insta/dto/article/ArticleRequestDto.java
  src/main/java/com/insta/dto/article/ArticleResponseDto.java
  src/main/java/com/insta/dto/comment/CommentRequestDto.java
  src/main/java/com/insta/dto/comment/CommentResponseDto.java
  src/main/java/com/insta/dto/comment/ReplyResponseDto.java
  src/main/java/com/insta/global/error/exception/ErrorCode.java
  src/main/java/com/insta/jwt/JwtAuthenticationFilter.java
  src/main/java/com/insta/jwt/JwtTokenProvider.java
  src/main/java/com/insta/model/Article.java
  src/main/java/com/insta/model/Comment.java
  src/main/java/com/insta/model/User.java
  src/main/java/com/insta/repository/CommentRepo.java
  src/main/java/com/insta/repository/UserRepository.java
  src/main/java/com/insta/security/UserDetailsImpl.java
  src/main/java/com/insta/security/UserDetailsServiceImpl.java
  src/main/java/com/insta/security/WebSecurityConfig.java
  src/main/java/com/insta/service/ArticleService.java
  src/main/java/com/insta/service/CommentService.java
  src/main/java/com/insta/service/UserService.java
Labels: enhancement

#32 유저 관련 로직 추가 및 리팩토링
  build.gradle
  src/main/java/com/insta/auth/SignupRequestDto.java
  src/main/java/com/insta/config/SwaggerConfig.java
  src/main/java/com/insta/controller/UserController.java
  src/main/java/com/insta/dto/auth/SignupRequestDto.java
  src/main/java/com/insta/dto/user/LoginRequestDto.java
  src/main/java/com/insta/dto/user/LoginResponseDto.java
  src/main/java/com/insta/dto/user/SignupRequestDto.java
  src/main/java/com/insta/global/error/GlobalExceptionHandler.java
  src/main/java/com/insta/global/error/exception/ErrorCode.java
  src/main/java/com/insta/model/User.java
  src/main/java/com/insta/repository/UserRepository.java
  src/main/java/com/insta/security/UserDetailsServiceImpl.java
  src/main/java/com/insta/security/WebSecurityConfig.java
  src/main/java/com/insta/service/UserService.java
Labels: bug, enhancement

#35 게시글/댓글 관련 인증 로직 추가
  README.md
  src/main/java/com/insta/model/Article.java
  src/main/java/com/insta/model/Comment.java
  src/main/java/com/insta/service/ArticleService.java
  src/main/java/com/insta/service/CommentService.java
Labels: enhancement

#37 게시글 제목 제거
  src/main/java/com/insta/dto/article/ArticleDetailResponseDto.java
  src/main/java/com/insta/dto/article/ArticleRequestDto.java
  src/main/java/com/insta/model/Article.java
  src/main/java/com/insta/service/ArticleService.java
Labels: bug

#40 게시글 전체 조회 시, 슬라이싱 처리
  src/main/java/com/insta/controller/ArticleController.java
  src/main/java/com/insta/repository/ArticleRepo.java
  src/main/java/com/insta/service/ArticleService.java
Labels: enhancement

#39 댓글/대댓글 전체 조회 시, 슬라이싱 처리
  src/main/java/com/insta/controller/CommentController.java
  src/main/java/com/insta/repository/CommentRepo.java
  src/main/java/com/insta/service/CommentService.java
Labels: enhancement

#44 좋아요 기능 추가
  src/main/java/com/insta/controller/ArticleController.java
  src/main/java/com/insta/controller/CommentController.java
  src/main/java/com/insta/dto/article/ArticleDetailResponseDto.java
  src/main/java/com/insta/dto/article/ArticleResponseDto.java
  src/main/java/com/insta/dto/comment/CommentResponseDto.java
  src/main/java/com/insta/dto/comment/ReplyResponseDto.java
  src/main/java/com/insta/model/Article.java
  src/main/java/com/insta/model/Comment.java
  src/main/java/com/insta/model/Heart.java
  src/main/java/com/insta/model/User.java
  src/main/java/com/insta/repository/ArticleRepo.java
  src/main/java/com/insta/repository/CommentRepo.java
  src/main/java/com/insta/repository/LikeRepo.java
  src/main/java/com/insta/service/ArticleService.java
  src/main/java/com/insta/service/CommentService.java
Labels: enhancement

#46 스웨거 추가
  src/main/java/com/insta/controller/ArticleController.java
  src/main/java/com/insta/controller/CommentController.java
Labels: documentation

#49 리프레시 토큰
  src/main/java/com/insta/config/WebConfig.java
  src/main/java/com/insta/controller/UserController.java
  src/main/java/com/insta/dto/user/TokenResponseDto.java
  src/main/java/com/insta/jwt/JwtTokenProvider.java
  src/main/java/com/insta/model/RefreshToken.java
  src/main/java/com/insta/repository/RefreshTokenRepository.java
  src/main/java/com/insta/service/UserService.java
Labels: enhancement

#52 조회용 API 추가
  src/main/java/com/insta/controller/ArticleController.java
  src/main/java/com/insta/controller/CommentController.java
  src/main/java/com/insta/dto/article/LikesResponseDto.java
  src/main/java/com/insta/repository/ArticleRepo.java
  src/main/java/com/insta/service/ArticleService.java
Labels: enhancement

#54 유저 정보 조회 API 추가
  src/main/java/com/insta/controller/UserController.java
  src/main/java/com/insta/dto/user/InfoResponseDto.java
  src/main/java/com/insta/model/User.java
  src/main/java/com/insta/service/UserService.java
Labels: enhancement

#59 스웨거 문제로 매핑 주소 변경
  README.md
  src/main/java/com/insta/controller/ArticleController.java
Labels: bug

#62 이미지 관련 작업
  build.gradle
  src/main/java/com/insta/config/AwsS3Config.java
  src/main/java/com/insta/controller/ArticleController.java
  src/main/java/com/insta/controller/UserController.java
  src/main/java/com/insta/dto/article/ArticleDetailResponseDto.java
  src/main/java/com/insta/dto/article/ArticleResponseDto.java
  src/main/java/com/insta/dto/user/InfoRequestDto.java
  src/main/java/com/insta/dto/user/InfoResponseDto.java
  src/main/java/com/insta/model/Image.java
  src/main/java/com/insta/model/ImageTarget.java
  src/main/java/com/insta/model/User.java
  src/main/java/com/insta/repository/ImageRepo.java
  src/main/java/com/insta/service/ArticleService.java
  src/main/java/com/insta/service/S3Service.java
  src/main/java/com/insta/service/UserService.java
  src/main/resources/application-prod.yaml
Labels: enhancement

#64 인코딩 필터 처리 추가
  src/main/java/com/insta/InstaBackendApplication.java
Labels: bug
